version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dr_piscinas_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-drPiscinas}
      POSTGRES_PASSWORD: ${DB_PASS:-administrador}
      POSTGRES_DB: ${DB_NAME:-drPiscinas_db}
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  web:
    build: .
    container_name: dr_piscinas_app
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-drPiscinas}:${DB_PASS:-administrador}@db:5432/${DB_NAME:-drPiscinas_db}
      - SECRET_KEY=${SECRET_KEY}
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "5000:5000"
    volumes:
      - .:/sistema
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro