version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dr_piscinas_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Mantenemos la ruta que definiste para la nueva VPS
      - /vps/clientes/drPiscinas/db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: dr_piscinas_app
    restart: always
    depends_on:
      - db
    # Cargamos el archivo .env automáticamente
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - /vps/clientes/drPiscinas:/sistema